# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.IntegerField()),
                ('apuesta', models.CharField(max_length=30)),
                ('bien', models.IntegerField()),
                ('regular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('incognita', models.PositiveIntegerField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Registrando', 'Registrando'), ('Jugando', 'Jugando'), ('Finalizado', 'Finalizado')], default='Registrando', max_length=25)),
                ('participantes', models.ManyToManyField(related_name='partidas', to='juego.Jugador')),
                ('turno_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juego.Jugador')),
            ],
        ),
    ]
