# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugada',
            name='jugador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juego.Jugador'),
        ),
        migrations.AddField(
            model_name='jugada',
            name='partida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juego.Partida'),
        ),
    ]
