# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_auto_20160815_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugada',
            name='apuesta',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='incognita',
            field=models.CharField(max_length=4),
        ),
    ]
