# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_auto_20160815_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='ronda',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jugada',
            name='ronda',
            field=models.PositiveIntegerField(),
        ),
    ]
