# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0004_auto_20160815_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='codigo',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='privado',
            field=models.BooleanField(default=False),
        ),
    ]
