# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0006_auto_20160826_2221'),
        ('juego', '0005_auto_20160909_2244'),
    ]

    operations = [
    ]
